apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forum-watcher-state-pvc
  namespace: group-tech-sales
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi